ensure_path( 'TEXINPUTS', './/' );
ensure_path( 'TEXINPUTS', '../../share//' );
ensure_path( 'TEXINPUTS', '../../units//' );


$pdflatex = "pdflatex -synctex=1  -halt-on-error %O %S";

$pdf_mode = 1;
$pdf_previewer = 'okular';
